services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: hwi_db
      MYSQL_USER: hwi_db_user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%' 
    ports: ['3306:3306']

  mealplan:
    command: bash -c "python manage.py migrate"
    restart: always
    environment:
      DJANGO_SUPERUSER_PASSWORD: 123456x
      DJANGO_SUPERUSER_EMAIL: admin@admin.org
      DJANGO_SUPERUSER_USERNAME: admin
    image: fknupper/mealplan:latest
    ports:
      - "8000:8000"
    depends_on:
      - mysql